spring.application.name=ReservaCasaRurales

# Conexión dinámica con Railway (NO localhost)
spring.datasource.url=jdbc:mariadb://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# Puerto dinámico (OBLIGATORIO en Railway)
server.port=${PORT:8080}

# ?PA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=false

# Logs
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.type.descriptor.sql=OFF
logging.level.org.hibernate.orm.jdbc.bind=OFF
logging.level.org.hibernate.stat=OFF